# Generated by Django 5.2.6 on 2025-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_uuid',
            field=models.CharField(default='0eac5c45-d5cb-410e-8eb8-64c0e3e06860', max_length=128, unique=True),
        ),
    ]
