# Generated by Django 5.2.6 on 2025-11-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default='982abf79aaa70dae1dad7b69600a1295', max_length=64, unique=True),
        ),
    ]
