# Generated by Django 5.2.6 on 2025-11-26 17:34

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=secrets.token_hex, max_length=64, unique=True),
        ),
    ]
