# Generated by Django 5.2.6 on 2025-10-31 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_chat_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
