# Generated by Django 5.2.6 on 2025-11-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_usertoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
