# Generated by Django 5.2.6 on 2025-11-07 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('chat', '0005_alter_chat_chat_uuid'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='UserOnlineStatus',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('online_status', models.BooleanField(default=False)),
				(
					'user',
					models.OneToOneField(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='status',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
	]
