# Generated by Django 5.2.6 on 2025-11-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_useronlinestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_private',
        ),
    ]
